collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.4751245
color:
  saturation: 0.8959088
  brandStrength: 1
  rhythmicContrast: 0.06815362
  brandColors:
    - '#232020'
    - '#DB2522'
    - '#FFFFFF'
    - '#FFE22E'
    - '#F1A3A5'
  lightness: 0.4296815
layout_spectrum: 0.3502506
name: banjansit
