layout_spectrum: 1
typography_spectrum: 0.4751245
color:
  saturation: 0.8959088
  lightness: 0.4296815
  brandStrength: 1
  brandColors:
    - '#232020'
    - '#DB2522'
    - '#FFFFFF'
    - '#FFE22E'
    - '#F1A3A5'
  rhythmicContrast: 0.06815362
name: banjansit
